[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

build_flags =
    -DUSE_ADC_MIC

board_build.partitions = huge_app.csv

monitor_speed = 115200
monitor_port = /dev/ttyUSB1
upload_speed = 921600